runtime: python27
api_version: 1
threadsafe: true
instance_class: B8


handlers:
- url: /css
  static_dir: static/bootstrap/css

- url: /js
  static_dir: static/js

- url: /static
  static_dir: static

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest